inducing_rows: 9
inducing_cols: 9
whitened_u: true
q_inducing: "diagonal"
learn_lamda: true
init_lamda: 0.001
max_lamda: 0.03
max_sd_u: 0.1
cache_cholesky: true
prior_sd: 0.1
sqrt_width_scaling: true
key_layers: ["q_proj", "k_proj", "lm_head"]
